standard = "2019"

[libraries]
xil_defaultlib.files = ['targets/**/*.vhd', 'shared/**/*.vhd']

# Ruckus
ruckus.files = ['build/*/*.srcs/*.vhd']
ruckus.is_third_party = true

# Surf
surf.files = [
    'submodules/surf/axi/**/*.vhd',
    'submodules/surf/base/**/*.vhd',
    'submodules/surf/dsp/**/*.vhd',
    'submodules/surf/devices/**/*.vhd',
    'submodules/surf/ethernet/**/*.vhd',
    'submodules/surf/protocols/**/*.vhd',
    'submodules/surf/xilinx/**/*.vhd',
]
surf.is_third_party = true

# Unisim
UNISIM.files = ['$XILINX_VIVADO/data/vhdl/src/unisims/unisim_VCOMP.vhd']
UNISIM.is_third_party = true

# XPM
xpm.files = ['$XILINX_VIVADO/data/ip/xpm/xpm_VCOMP.vhd']
xpm.is_third_party = true

[lint]
misplaced_attribute_spec = false
