[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    # "-C",
    # "relocation-model=pie",
    "-C",
    "link-arg=--emit-relocs",
]
runner = "just rust"

[build]
target = "riscv32i-unknown-none-elf"
