[workspace]
resolver = "3"
members = ["common", "samples", "bootloader", "nightly_pie"]

[patch.crates-io]
riscv-rt = { git = 'https://github.com/rust-embedded/riscv' }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
